spring:
  datasource:
    url: jdbc:mysql://localhost:3306/author_book_rest
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: YBCcy67GtDm556ixLOQAhIoma745zIztvfArTM1oL8f29BjKB9If3abNRg0Y5mzQAANRg0Y5mzQAANRg0Y5mzQAA
  expiration: 600000

upload:
  image:
    path: /Users/narekgalstyan/Documents/IdeaProjects/rest/author-book-rest/images

cb:
  armUrl: https://cb.am/latest.json.php

rapid:
  getAllCountries:
    url: https://geography4.p.rapidapi.com/apis/geography/v1/country
    key:
      apiKey: X-RapidAPI-Key
      value: 2dac9d0703msha977a878b65e0bbp15b0abjsn3c66e9356536
    host:
      key: X-RapidAPI-Host
      value: geography4.p.rapidapi.com