spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:

jwt:
  secret:
  expiration:

upload:
  image:
    path:

cb:
  armUrl:

rapid:
  getAllCountries:
    url:
    key:
      apiKey:
      value:
    host:
      key:
      value: